// Based on current data flows; operator verification is tracked in docs/privacy-review.md.
type Section = { id: string; title: string; paragraphs: string[]; links?: { label: string; href: string }[] };
type StorageEntry = { name: string; purpose: string; duration: string };
type Notice = {
  title: string; description: string; updated: string; contents: string;
  contactLabel: string; country: string;
  storageHeaders: [string, string, string]; storage: StorageEntry[]; sections: Section[];
};
const providers = {
  vercel: 'https://vercel.com/legal/privacy-notice', neon: 'https://neon.com/privacy-policy',
  stripe: 'https://stripe.com/de/privacy', resend: 'https://resend.com/legal/privacy-policy',
  cloudflare: 'https://www.cloudflare.com/privacypolicy/', cloudinary: 'https://cloudinary.com/privacy',
  unsplash: 'https://unsplash.com/privacy', google: 'https://policies.google.com/privacy',
};

export const privacyNotices: Record<'de' | 'en', Notice> = {
  de: {
    title: 'Datenschutzerklärung',
    description: 'Datenschutz bei Maurer Events: Website, Kontakt, Reservierungen, Zahlungen, Tickets und Einlass-Team.',
    updated: 'Stand: 7. Oktober 2026', contents: 'Inhalt', contactLabel: 'E-Mail für Datenschutzanfragen', country: 'Deutschland',
    storageHeaders: ['Speicher / Bezeichnung', 'Zweck und Inhalt', 'Gültigkeit / Speicherdauer'],
    storage: [
      { name: 'Sprach-Cookie (NEXT_LOCALE)', purpose: 'Merkt die ausgewählte Sprache Deutsch oder Englisch, wenn sie von der erkannten Sprache abweicht.', duration: 'Sitzungs-Cookie ohne festes Ablaufdatum; die tatsächliche Dauer hängt auch von der Sitzungswiederherstellung Ihres Browsers ab.' },
      { name: 'Login-Cookie (admin_token)', purpose: 'Zufällige Sitzungskennung für den Festwirt- und Scanner-Zugang. Für JavaScript nicht lesbar; im HTTPS-Betrieb geschützt übertragen.', duration: 'Höchstens sieben Tage, bei Abmeldung entfernt. Widerruf oder Ablauf der Scanner-Freigabe sperrt den Zugang unabhängig vom Cookie.' },
      { name: 'Sitzungsspeicher (reservation-checkout-attempt)', purpose: 'Bei Zahlungsbeginn: Wiederholungskennung sowie Name, E-Mail, Veranstaltung, Tag, Uhrzeit, Gästezahl, Paket und gegebenenfalls Tisch. Dient der Zuordnung wiederholter Anfragen zur selben Buchung.', duration: 'Für die Browser-Tab-Sitzung; bei bestimmten abgelaufenen Buchungsversuchen entfernt. Kann beim Wiederherstellen eines Tabs fortbestehen.' },
    ],
    sections: [
      { id: 'verantwortlich', title: '1. Verantwortlicher und Kontakt', paragraphs: [
        'Diese Erklärung beschreibt die Verarbeitung personenbezogener Daten beim Websitebesuch, bei Kontaktanfragen, Bewerbungen, Reservierungen, Zahlungen, Wartelisteneinträgen und beim Ticket-Einlass. Personenbezogene Daten sind Informationen über eine bestimmte oder bestimmbare Person.',
        'Verantwortlich für die Verarbeitung durch Maurer Events ist Florian Maurer. Die folgende Kontaktadresse können Sie auch für Auskunft, Berichtigung, Löschung und andere Datenschutzanliegen verwenden.',
      ] },
      { id: 'hosting', title: '2. Website-Betrieb und Zugriffsdaten', paragraphs: [
        'Die Website wird über Vercel (Vercel Inc., USA) bereitgestellt. Beim Abruf verarbeiten die beteiligten Server insbesondere IP-Adresse, Zeitpunkt, angeforderte Adresse, HTTP-Methode und Status, Browser- und Geräteinformationen sowie gegebenenfalls die zuvor besuchte Seite. Technische Protokolle unterstützen die Auslieferung, Fehleranalyse und Abwehr missbräuchlicher Zugriffe.',
        'Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO. Unser berechtigtes Interesse ist eine verfügbare, zuverlässige und sichere Website. Protokolldaten unterliegen den für den Hostingdienst und Sicherheitszweck geltenden Speicherfristen. Konkrete Sicherheitsvorfälle können längere Aufbewahrung zur Aufklärung oder Rechtsverfolgung erfordern.',
      ], links: [{ label: 'Datenschutzhinweise von Vercel', href: providers.vercel }] },
      { id: 'browser-speicher', title: '3. Cookies und Browser-Speicher', paragraphs: [
        'Für Spracheinstellung, Anmeldung und die sichere Wiederholung einer von Ihnen gestarteten Buchung verwenden wir die unten beschriebenen Speicherfunktionen. Die Website setzt derzeit keine eigenen Analyse- oder Werbetracking-Cookies ein. Zusätzlich beteiligte Sicherheits- und Zahlungsdienste sind in den jeweiligen Abschnitten beschrieben.',
        'Soweit Speicherung oder Zugriff für eine ausdrücklich gewünschte Funktion unbedingt erforderlich sind, gilt § 25 Abs. 2 Nr. 2 TDDDG. Die weitere Verarbeitung personenbezogener Daten beruht je nach Zweck auf Art. 6 Abs. 1 lit. b DSGVO für Buchungen beziehungsweise Art. 6 Abs. 1 lit. f DSGVO für Spracheinstellung und Zugangssicherheit. Nicht erforderliche Speicherzugriffe bedürfen einer Einwilligung nach § 25 Abs. 1 TDDDG.',
        'Sie können Cookies und Sitzungsspeicher im Browser löschen oder beschränken. Dadurch können Spracheinstellung, Login oder die zuverlässige Wiederholung einer begonnenen Zahlung eingeschränkt sein.',
      ] },
      { id: 'kontakt-bewerbung', title: '4. Kontaktanfragen und Bewerbungen', paragraphs: [
        'Im Kontaktformular verarbeiten wir Name beziehungsweise Firma, E-Mail-Adresse, Veranstaltungsart und Nachricht. Bei E-Mail-Anfragen verarbeiten wir auch übersandte Inhalte und Anhänge. Zweck ist die Bearbeitung, Angebotserstellung und Beantwortung von Rückfragen. Vertragsbezogene Anfragen beruhen auf Art. 6 Abs. 1 lit. b DSGVO; sonstige Kommunikation auf unserem berechtigten Interesse nach Art. 6 Abs. 1 lit. f DSGVO. Das Kontaktformular sendet Ihre Angaben über Resend an unser Kontaktpostfach.',
        'Die Karriereseite ermöglicht Bewerbungen per E-Mail. Wir verarbeiten die bereitgestellten Kontakt-, Qualifikations- und Bewerbungsdaten zur Entscheidung über ein Beschäftigungsverhältnis nach § 26 Abs. 1 BDSG und, soweit einschlägig, Art. 6 Abs. 1 lit. b DSGVO. Ein längerfristiger Bewerberpool setzt eine gesonderte freiwillige Einwilligung voraus.',
        'Die Speicherdauer richtet sich nach Bearbeitung und Abschluss des Anliegens beziehungsweise Bewerbungsverfahrens. Darüber hinaus können gesetzliche Pflichten oder die Geltendmachung beziehungsweise Abwehr von Ansprüchen eine Aufbewahrung erfordern. Bitte senden Sie nur Angaben, die für Ihr Anliegen erforderlich sind.',
      ] },
      { id: 'buchung-warteliste', title: '5. Reservierungen, Warteliste und Datenbank', paragraphs: [
        'Für Reservierungen verarbeiten wir Namen und E-Mail-Adresse der buchenden Person, Gästezahl, Veranstaltung, Datum, Uhrzeit, Paket, gegebenenfalls Tisch, Gesamtpreis sowie Buchungs-, Zahlungs- und Versandstatus. Technische Buchungs- und Zahlungskennungen dienen der Zuordnung und Vermeidung doppelter Buchungen. Der Festwirt kann Reservierungen auch im Auftrag von Gästen manuell anlegen.',
        'Zweck ist die Vorbereitung und Erfüllung des Buchungsvertrags einschließlich Kapazitätsplanung, Bestätigung, Änderungen, Zahlungsabgleich und Einlass nach Art. 6 Abs. 1 lit. b DSGVO. Gesetzliche Dokumentation beruht auf Art. 6 Abs. 1 lit. c DSGVO, Missbrauchsabwehr und nachvollziehbare Abläufe auf Art. 6 Abs. 1 lit. f DSGVO.',
        'Für die Warteliste speichern wir Namen, E-Mail-Adresse, Gästezahl, Veranstaltung, Eintragszeitpunkt und gegebenenfalls Benachrichtigungszeitpunkt. Damit informieren wir Sie über frei gewordene Plätze für diese Veranstaltung. Ein Eintrag begründet keine Buchung und ist keine Newsletter-Anmeldung. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO für die gewünschte Buchungsanbahnung. Zur Entfernung des Eintrags können Sie uns kontaktieren.',
        'Die Anwendungsdaten liegen in einer PostgreSQL-Datenbank des Dienstes Neon, der zur Databricks-Gruppe gehört. Der Dienst verarbeitet gespeicherte Inhalte und technische Verbindungsdaten für den Datenbankbetrieb. Neons aktuelle Datenschutzseite verweist auf die Datenschutzhinweise von Databricks.',
        'Name, E-Mail-Adresse und die erforderlichen Buchungsangaben werden benötigt, um Ihre Reservierung zuzuordnen und das Ticket zuzustellen. Ohne diese Angaben sind Onlinebuchung beziehungsweise Wartelistenaufnahme nicht möglich.',
      ], links: [{ label: 'Datenschutzhinweise von Neon / Databricks', href: providers.neon }] },
      { id: 'zahlung', title: '6. Zahlung mit Stripe', paragraphs: [
        'Kostenpflichtige Buchungen werden über Stripe Checkout bezahlt. An Stripe übermitteln wir insbesondere E-Mail-Adresse, Buchungskennung, Leistungsbeschreibung, Gästezahl, Preis und gegebenenfalls VIP- und Servicegebühren. Zahlungsangaben wie Kartendaten oder Bankverbindung geben Sie auf der Zahlungsseite ein; vollständige Zahlungsdaten speichern wir nicht in unserer Reservierungsdatenbank.',
        'Stripe meldet Zahlungs- und Erstattungsstatus sowie Zahlungskennungen zurück. Wir benötigen sie zur Bestätigung, Ticketausstellung, Rückzahlung und Klärung von Zahlungsproblemen. Je nach Zahlungsart können weitere Anbieter, etwa PayPal, Klarna oder Banken, Daten verarbeiten. Deren Hinweise werden im Zahlungsablauf bereitgestellt.',
        'Unsere Vertragsabwicklung beruht auf Art. 6 Abs. 1 lit. b DSGVO, Nachweispflichten auf Art. 6 Abs. 1 lit. c DSGVO und Betrugsabwehr auf Art. 6 Abs. 1 lit. f DSGVO. Stripe handelt je nach Verarbeitung als Auftragsverarbeiter oder eigenständig Verantwortlicher, insbesondere für eigene gesetzliche Pflichten und Betrugsprävention. Die zuständige Stripe-Gesellschaft und weitere Verarbeitung beschreibt das Stripe-Datenschutzcenter.',
      ], links: [{ label: 'Datenschutzerklärung und Datenschutzcenter von Stripe', href: providers.stripe }] },
      { id: 'ticket-einlass', title: '7. Tickets, QR-Code und Einlass', paragraphs: [
        'Das PDF-Ticket enthält Veranstaltungsname, Datum, gegebenenfalls Uhrzeit und Ort, Gastname, Gästezahl, Tisch beziehungsweise freie Platzwahl und einen zufälligen Ticketcode als QR-Code. Dieser ermöglicht die Zuordnung zur Buchung. Behandeln Sie den Code wie ein Zugangsticket und veröffentlichen Sie ihn nicht.',
        'Beim Scan werden Ticket, Buchung und Berechtigung der scannenden Person geprüft. Ein erfolgreicher Check-in speichert Einlassstatus und Zeitpunkt. Zeitlich begrenzt für einzelne Feste freigegebene Helfer sehen nach erfolgreichem Scan Gastname, Gästezahl und Tisch sowie beim übergreifenden Scanner den Veranstaltungsnamen. Sie erhalten keinen Zugriff auf Gästelisten, E-Mail-Adressen, Umsätze oder Verwaltungseinstellungen.',
        'Der Kamerascanner benötigt eine Browser-Kamerafreigabe. Die QR-Erkennung erfolgt lokal auf dem verwendeten Gerät. Die Scanner-Funktion zeichnet keine Fotos oder Videos auf und lädt keine Kamerabilder auf unsere Server hoch. Nur der erkannte Code wird zur Ticketprüfung übertragen. Die Kamerafreigabe können Sie im Browser jederzeit entziehen.',
        'Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b DSGVO für den vereinbarten Einlass und Art. 6 Abs. 1 lit. f DSGVO für die Vermeidung mehrfacher oder unberechtigter Nutzung und die Beschränkung des Helferzugriffs.',
      ] },
      { id: 'email-login', title: '8. E-Mail-Versand und Team-Login', paragraphs: [
        'Resend (Plus Five Five, Inc., USA) versendet Kontaktformular-Nachrichten, Buchungs- und Ticketmails, veranstaltungsbezogene Wartelistenhinweise sowie einmalige Login-Codes. Dabei verarbeitet Resend Absender, Empfänger, gegebenenfalls Antwortadresse, Nachrichteninhalt, Ticketanhang und Zustellinformationen. Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b DSGVO für angefragte Kommunikation und Vertragsabwicklung beziehungsweise Art. 6 Abs. 1 lit. f DSGVO für sichere Zugänge.',
        'Beim Festwirt- und Scanner-Login verarbeiten wir E-Mail-Adresse, kryptografisch geschützten Code-Prüfwert, Fehlversuche, Ablaufzeit und Sitzungskennung. Codes gelten zehn Minuten und werden bei erfolgreicher Verwendung verbraucht. Sitzungen gelten höchstens sieben Tage. Scanner-Freigaben enthalten E-Mail-Adresse, Veranstaltung, Ablaufdatum, freigebende Person und Anlegezeitpunkt. Sie gelten höchstens 90 Tage und können vorher widerrufen werden.',
        'Abgelaufene Codes und Sitzungen erlauben keinen Zugang mehr. Die Anwendung unterstützt die Bereinigung abgelaufener Anmeldedaten. Zugangssperre und Löschung anderer Vertrags- oder Sicherheitsdaten sind unterschiedliche Vorgänge.',
      ], links: [{ label: 'Datenschutzhinweise von Resend', href: providers.resend }] },
      { id: 'spam-schutz', title: '9. Spam- und Missbrauchsschutz', paragraphs: [
        'Kontaktformular, Buchung, Warteliste und Team-Login verwenden Cloudflare Turnstile (Cloudflare, Inc., USA). Beim Laden und Prüfen des Widgets verarbeitet Cloudflare insbesondere IP-Adresse, Browser- und Geräteinformationen sowie Signale zur Unterscheidung menschlicher und automatisierter Zugriffe. Unser Server übermittelt den Prüftoken und prüft das Ergebnis für unsere Domain und Formularfunktion.',
        'Zusätzlich begrenzen wir wiederholte Anfragen. Hierfür speichern wir einen aus E-Mail-Adresse und Vorgang abgeleiteten Hashwert, einen Zähler und den Ablauf des Prüfzeitfensters. Diese Kennungen bleiben personenbezogene beziehungsweise pseudonyme Daten. Die Anfragefenster betragen derzeit 15 Minuten; abgelaufene Einträge können beim Bereinigungslauf entfernt werden.',
        'Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO. Unser Interesse ist Schutz vor Spam, automatisierten Buchungen, unberechtigten Anmeldungen und Überlastung. Soweit der Dienst für eine ausdrücklich gewünschte Funktion unbedingt erforderliche Geräteinformationen speichert oder ausliest, gilt § 25 Abs. 2 Nr. 2 TDDDG. Eine Browserfreigabe oder ein CAPTCHA ersetzt keine gegebenenfalls erforderliche datenschutzrechtliche Einwilligung.',
      ], links: [{ label: 'Datenschutzhinweise von Cloudflare', href: providers.cloudflare }] },
      { id: 'bilder-inhalte', title: '10. Bilder, Galerie, Links und Übersetzungen', paragraphs: [
        'Bilder und Veranstaltungsfotos werden über unsere Website und Cloudinary (Cloudinary Ltd. und verbundene Unternehmen) bereitgestellt. Cloudinary verarbeitet Bilddateien und Abrufdaten für Speicherung, Optimierung und Auslieferung. Einzelne Homepagebilder sind mit Unsplash als externer Bildquelle hinterlegt. Wenn Ihr Browser externe Bilder direkt abruft, erhält der Bildanbieter insbesondere IP-Adresse, Browserinformationen und gegebenenfalls den Ursprung des Abrufs. Die Bereitstellung beruht auf Art. 6 Abs. 1 lit. f DSGVO und unserem Interesse an der Darstellung unseres Angebots.',
        'Bei erkennbaren Personen ist auch die Fotoveröffentlichung eine Verarbeitung personenbezogener Daten. Je nach Bild und Kontext kommen eine Einwilligung nach Art. 6 Abs. 1 lit. a DSGVO oder nach erforderlicher Interessenabwägung Art. 6 Abs. 1 lit. f DSGVO in Betracht. Für Fragen, Widerruf oder Widerspruch nennen Sie uns bitte die Galerie oder Bildadresse.',
        'Social-Media-Verweise, insbesondere Instagram und TikTok, sind Links. Wenn Sie ihnen folgen, gelten die Datenschutzhinweise der Plattformbetreiber. Schriftdateien werden mit der Website ausgeliefert; für die Anzeige muss Ihr Browser keine Google-Fonts-Server kontaktieren.',
        'Die Inhaltsverwaltung unterstützt automatische Übersetzungen über Google Gemini, sofern eingerichtet. Beim Anlegen oder Bearbeiten werden Veranstaltungs- und Galerietexte wie Titel, Ort und Beschreibung an Google übermittelt. Die Funktion übermittelt keine Reservierungsdatensätze, Login-Codes oder Scanner-Kamerabilder. Zweck ist die mehrsprachige Darstellung veröffentlichter Inhalte; für enthaltene personenbezogene Angaben gilt Art. 6 Abs. 1 lit. f DSGVO.',
      ], links: [{ label: 'Datenschutzhinweise von Cloudinary', href: providers.cloudinary }, { label: 'Datenschutzhinweise von Unsplash', href: providers.unsplash }, { label: 'Datenschutzhinweise von Google', href: providers.google }] },
      { id: 'empfaenger-drittlaender', title: '11. Empfänger und internationale Verarbeitung', paragraphs: [
        'Empfänger sind zuständige Personen bei Maurer Events, freigegebene Einlasshelfer im beschriebenen Umfang und die genannten Hosting-, Datenbank-, Medien-, Sicherheits-, E-Mail- und Zahlungsdienste. Behörden oder fachliche Berater können bei berechtigten gesetzlichen Anforderungen Daten erhalten. Zahlungsanbieter können für eigene Zwecke selbst verantwortlich sein.',
        'Mehrere Anbieter sitzen außerhalb der EU beziehungsweise des EWR oder setzen dort Support und Unterauftragnehmer ein. Eine Verarbeitung insbesondere in den USA und bei Cloudinary auch in Israel ist möglich. Ein EU-Datenbankstandort allein schließt Drittlandzugriffe nicht aus.',
        'Drittlandübermittlungen setzen Art. 44 ff. DSGVO voraus. Je nach Land und Empfänger kommen Angemessenheitsbeschlüsse, bei entsprechend zertifizierten US-Empfängern das EU-US Data Privacy Framework oder Standardvertragsklauseln mit erforderlichen ergänzenden Maßnahmen in Betracht. Informationen zu den für Ihre Daten maßgeblichen Empfängern, Verarbeitungsorten und Garantien sowie eine Kopie zugänglicher Garantien können Sie über unsere Kontaktadresse anfragen.',
      ] },
      { id: 'speicherdauer', title: '12. Speicherdauer und Löschung', paragraphs: [
        'Die Speicherdauer richtet sich nach Zweck, Bearbeitungsstand und gesetzlichen Pflichten. Reservierungs- und Ticketdaten werden für Buchung, Veranstaltung, Zahlungsabgleich und gegebenenfalls spätere Rückfragen oder Ansprüche benötigt. Ein abgelaufenes Ticket oder ein abgelaufener Scanner-Zugang löscht nicht automatisch sämtliche zugehörigen Daten.',
        'Für steuer- und handelsrechtliche Unterlagen gelten die jeweiligen Fristen aus § 147 AO beziehungsweise § 257 HGB: grundsätzlich acht Jahre für Buchungsbelege, sechs Jahre für Handels- und Geschäftsbriefe und zehn Jahre für Bücher und bestimmte weitere Unterlagen. Fristbeginn ist regelmäßig das Ende des maßgeblichen Kalenderjahres. Diese Pflichten rechtfertigen keine pauschale gleich lange Aufbewahrung sämtlicher Browserkennungen, Login-Codes oder Ticketangaben.',
        'Daten ohne fortbestehenden Zweck oder Aufbewahrungspflicht sind zu löschen oder zu anonymisieren. Laufende Ansprüche oder Verfahren können weitere Aufbewahrung erfordern. Sicherungskopien und Protokolle können nach ihrem Aufbewahrungszyklus zeitversetzt auslaufen. Kontaktieren Sie uns, um die Speicherdauer oder Löschung eines konkreten Vorgangs zu klären.',
      ] },
      { id: 'rechte', title: '13. Ihre Datenschutzrechte', paragraphs: [
        'Nach den gesetzlichen Voraussetzungen haben Sie Rechte auf Auskunft (Art. 15 DSGVO), Berichtigung (Art. 16), Löschung (Art. 17), Einschränkung (Art. 18) und Datenübertragbarkeit (Art. 20). Wenden Sie sich dafür an unsere Kontaktadresse. Falls erforderlich, bitten wir um geeignete Angaben zur Zuordnung und Identitätsprüfung.',
        'Einwilligungen können Sie jederzeit für die Zukunft widerrufen. Die Rechtmäßigkeit der vorherigen Verarbeitung bleibt unberührt.',
        'Bei Verarbeitung nach Art. 6 Abs. 1 lit. f DSGVO können Sie aus Gründen Ihrer besonderen Situation nach Art. 21 DSGVO widersprechen. Wir verarbeiten die betroffenen Daten dann nicht weiter, sofern keine zwingenden schutzwürdigen Gründe oder Gründe für Rechtsansprüche vorliegen. Gegen Direktwerbung ist jederzeit ein Widerspruch ohne Begründung möglich.',
        'Nach Art. 77 DSGVO können Sie sich bei einer Aufsichtsbehörde beschweren, insbesondere am Aufenthaltsort, Arbeitsplatz oder Ort des vermuteten Verstoßes. Für private Unternehmen in Bayern ist das Bayerische Landesamt für Datenschutzaufsicht (BayLDA) zuständig.',
      ], links: [{ label: 'Beschwerde beim BayLDA', href: 'https://www.lda.bayern.de/de/beschwerde.html' }] },
    ],
  },
  en: {
    title: 'Privacy Policy', description: 'Privacy at Maurer Events: website, enquiries, reservations, payments, tickets and admission staff.',
    updated: 'Last updated: 7 October 2026', contents: 'Contents', contactLabel: 'Email for privacy enquiries', country: 'Germany',
    storageHeaders: ['Storage / name', 'Purpose and contents', 'Validity / retention'],
    storage: [
      { name: 'Language cookie (NEXT_LOCALE)', purpose: 'Remembers selected German or English when it differs from the detected language.', duration: 'Session cookie without a fixed expiry; actual duration also depends on browser session restoration.' },
      { name: 'Login cookie (admin_token)', purpose: 'Random session identifier for organiser and scanner access. JavaScript cannot read it; securely transmitted over HTTPS.', duration: 'Up to seven days; removed on logout. Revoking or expiring scanner access blocks access independently of the cookie.' },
      { name: 'Session storage (reservation-checkout-attempt)', purpose: 'When payment starts: retry identifier, name, email, event, date, time, party size, package and table if applicable. Matches repeated requests to the same booking.', duration: 'For the browser tab session; removed for certain expired booking attempts. May persist when a tab is restored.' },
    ],
    sections: [
      { id: 'verantwortlich', title: '1. Controller and contact', paragraphs: [
        'This notice describes personal-data processing when you visit the website, send enquiries or job applications, make reservations or payments, join a waiting list or use ticket admission. Personal data is information relating to an identified or identifiable person.',
        'Florian Maurer is responsible for processing carried out by Maurer Events. Use the contact details below to request access, correction, deletion or exercise other privacy rights.',
      ] },
      { id: 'hosting', title: '2. Website hosting and access data', paragraphs: [
        'Vercel (Vercel Inc., USA) hosts and delivers the website. Servers process information including IP address, access time, requested URL, HTTP method and status, browser and device information and, where applicable, the referring page. Technical logs support delivery, troubleshooting and protection against abuse.',
        'The legal basis is Article 6(1)(f) GDPR. Our legitimate interest is an available, reliable and secure website. Logs follow retention periods applicable to the hosting service and security purpose. Specific incidents may require longer retention for investigation or legal claims.',
      ], links: [{ label: 'Vercel privacy notice', href: providers.vercel }] },
      { id: 'browser-speicher', title: '3. Cookies and browser storage', paragraphs: [
        'The storage functions below support language selection, login and safely retrying a booking you have started. The website currently uses no own analytics or advertising tracking cookies. Security and payment services are described in their respective sections.',
        'Strictly necessary storage or access for an expressly requested function falls under Section 25(2)(2) of the German TDDDG. Further personal-data processing relies on Article 6(1)(b) GDPR for bookings or Article 6(1)(f) GDPR for language preferences and access security. Non-essential storage access requires consent under Section 25(1) TDDDG.',
        'You can delete or restrict cookies and session storage in your browser. This may affect language settings, login or reliable retries of a payment you have started.',
      ] },
      { id: 'kontakt-bewerbung', title: '4. Enquiries and job applications', paragraphs: [
        'The contact form collects name or company, email, event type and message. For email enquiries, we also process the contents and attachments you send. We use this information to respond, prepare offers and clarify requests. Contract-related enquiries rely on Article 6(1)(b) GDPR; other communication relies on our legitimate interest under Article 6(1)(f) GDPR. The contact form sends your details to our inbox through Resend.',
        'The careers page allows applications by email. We process the contact, qualification and application information you provide to decide on employment under Section 26(1) of the German BDSG and, where applicable, Article 6(1)(b) GDPR. A longer-term applicant pool requires separate voluntary consent.',
        'Retention depends on processing and completion of the matter or recruitment process. Legal duties or establishing or defending claims may require further retention. Please send only information necessary for your request.',
      ] },
      { id: 'buchung-warteliste', title: '5. Reservations, waiting lists and database', paragraphs: [
        'Reservations involve the booking person’s name and email, party size, event, date, time, package, table if applicable, total price and booking, payment and delivery status. Technical booking and payment identifiers support matching and prevent duplicate bookings. The organiser may also enter bookings manually on behalf of guests.',
        'The purpose is preparing and fulfilling the booking contract, including capacity planning, confirmation, changes, payment reconciliation and admission under Article 6(1)(b) GDPR. Legal records rely on Article 6(1)(c) GDPR; abuse prevention and reliable processes on Article 6(1)(f) GDPR.',
        'Waiting-list entries contain name, email, party size, event, registration time and notification time if applicable. We use these to notify you about places for that event. An entry is neither a booking nor a newsletter subscription. The requested booking-related service relies on Article 6(1)(b) GDPR. Contact us to remove an entry.',
        'Application data is stored in a PostgreSQL database provided by Neon, part of the Databricks group. The service processes stored contents and technical connection data to operate the database. Neon’s current privacy page links to the Databricks notice.',
        'Your name, email and required booking details are necessary to identify your reservation and deliver its ticket. Without them, online bookings or waiting-list entries cannot be completed.',
      ], links: [{ label: 'Neon / Databricks privacy notice', href: providers.neon }] },
      { id: 'zahlung', title: '6. Stripe payments', paragraphs: [
        'Paid bookings use Stripe Checkout. We send information including email, booking identifier, service description, party size, price and any VIP or service fees to Stripe. Card or bank details are entered on the payment page; we do not store complete payment details in our reservation database.',
        'Stripe returns payment and refund status and payment identifiers. These support confirmation, ticket issuance, refunds and resolving payment problems. Other providers such as PayPal, Klarna or banks may process data depending on the payment method. Their notices are provided during payment.',
        'Our contract processing relies on Article 6(1)(b) GDPR, legal records on Article 6(1)(c) GDPR and fraud prevention on Article 6(1)(f) GDPR. Stripe may act as a processor or independent controller, particularly for its own legal duties and fraud prevention. Its privacy centre identifies the relevant Stripe entity and further processing.',
      ], links: [{ label: 'Stripe privacy policy and privacy centre', href: 'https://stripe.com/privacy' }] },
      { id: 'ticket-einlass', title: '7. Tickets, QR codes and admission', paragraphs: [
        'The PDF ticket contains event name, date, time and location where applicable, guest name, party size, table or unassigned seating and a random ticket identifier as a QR code. The code matches the booking. Treat it as an admission ticket and do not publish it.',
        'Scanning checks the ticket, booking and the scanning person’s permission. Successful check-in stores admission status and time. Helpers with time-limited access to individual events see guest name, party size and table after a successful scan, plus the event name in the general scanner. They cannot access guest lists, email addresses, revenue or administration settings.',
        'Camera scanning requires browser camera permission. QR recognition runs locally on the device. The scanner function does not record photos or videos or upload camera images to our servers. Only the recognised code is sent for validation. You can revoke camera permission in your browser.',
        'The legal bases are Article 6(1)(b) GDPR for agreed admission and Article 6(1)(f) GDPR to prevent repeated or unauthorised use and restrict helper access.',
      ] },
      { id: 'email-login', title: '8. Email delivery and staff login', paragraphs: [
        'Resend (Plus Five Five, Inc., USA) sends contact-form messages, booking and ticket emails, event-specific waiting-list notifications and one-time login codes. It processes sender, recipient, reply address where applicable, message contents, ticket attachment and delivery information. Article 6(1)(b) GDPR applies to requested communication and contract processing; Article 6(1)(f) GDPR to secure access.',
        'Organiser and scanner login involves email, cryptographically protected code verification value, failed attempts, expiry and session identifier. Codes last ten minutes and are consumed on successful use. Sessions last up to seven days. Scanner grants contain email, event, expiry, granting person and creation time. They last up to 90 days and may be revoked earlier.',
        'Expired codes and sessions no longer allow access. The application supports cleanup of expired login records. Blocking access and deleting other contractual or security data are separate processes.',
      ], links: [{ label: 'Resend privacy policy', href: providers.resend }] },
      { id: 'spam-schutz', title: '9. Spam and abuse prevention', paragraphs: [
        'The contact form, booking, waiting list and staff login use Cloudflare Turnstile (Cloudflare, Inc., USA). Loading and checking the widget processes information including IP address, browser and device information and signals to distinguish human from automated access. Our server sends the verification token and checks the result for our domain and form function.',
        'We also limit repeated requests using a hash derived from email and operation, a counter and the end of a checking window. These identifiers remain personal or pseudonymous data. Request windows currently last 15 minutes; expired records can be removed during cleanup.',
        'Article 6(1)(f) GDPR applies to our interest in protection against spam, automated bookings, unauthorised login and overload. Strictly necessary device storage or access for an expressly requested function falls under Section 25(2)(2) TDDDG. Browser permission or a CAPTCHA does not replace any data-protection consent that may be required.',
      ], links: [{ label: 'Cloudflare privacy policy', href: providers.cloudflare }] },
      { id: 'bilder-inhalte', title: '10. Images, galleries, links and translations', paragraphs: [
        'Images and event photographs are delivered through our website and Cloudinary (Cloudinary Ltd. and affiliates). Cloudinary processes image files and access data for storage, optimisation and delivery. Some homepage images reference Unsplash as an external source. If your browser directly requests external images, the provider receives information including IP address, browser details and potentially the request origin. Delivery relies on Article 6(1)(f) GDPR and our interest in presenting our services.',
        'Publishing images of identifiable people also processes personal data. Depending on image and context, consent under Article 6(1)(a) GDPR or Article 6(1)(f) GDPR following the required balancing of interests may apply. For questions, withdrawal or objections, please identify the gallery or image URL.',
        'Social-media references including Instagram and TikTok are links. Following them makes the platform’s privacy notice applicable. Font files are delivered with the website; displaying them does not require your browser to contact Google Fonts servers.',
        'Content administration supports automatic translations through Google Gemini when configured. Creating or editing content sends event and gallery text such as title, location and description to Google. The function does not send reservation records, login codes or scanner camera images. Its purpose is multilingual published content; Article 6(1)(f) GDPR applies to personal details included in it.',
      ], links: [{ label: 'Cloudinary privacy policy', href: providers.cloudinary }, { label: 'Unsplash privacy policy', href: providers.unsplash }, { label: 'Google privacy policy', href: providers.google }] },
      { id: 'empfaenger-drittlaender', title: '11. Recipients and international processing', paragraphs: [
        'Recipients include responsible staff at Maurer Events, authorised admission helpers within the limits described, and the hosting, database, media, security, email and payment services named above. Authorities or professional advisers may receive data where justified by legal requirements. Payment providers may be independent controllers for their own purposes.',
        'Several providers are based outside the EU or EEA or use support staff and subprocessors there. Processing may occur particularly in the USA and, for Cloudinary, also in Israel. An EU database location alone does not rule out third-country access.',
        'Third-country transfers require Articles 44 et seq. GDPR. Depending on country and recipient, instruments include adequacy decisions, the EU-US Data Privacy Framework for appropriately certified US recipients, or standard contractual clauses with necessary supplementary measures. Contact us for information about recipients, locations and safeguards applicable to your data and a copy of accessible safeguards.',
      ] },
      { id: 'speicherdauer', title: '12. Retention and deletion', paragraphs: [
        'Retention depends on purpose, processing status and legal duties. Reservation and ticket data supports booking, the event, payment reconciliation and potentially later enquiries or claims. Expiring a ticket or scanner access does not automatically delete all associated records.',
        'Sections 147 AO and 257 HGB provide the respective German tax and commercial retention periods: generally eight years for accounting vouchers, six for business correspondence and ten for books and certain other documents. Periods usually start at the end of the relevant calendar year. These duties do not justify keeping every browser identifier, login code or ticket detail for the same duration.',
        'Data without a continuing purpose or retention duty must be deleted or anonymised. Pending claims or proceedings may require further retention. Backups and logs may expire later in their retention cycle. Contact us to clarify retention or deletion for a specific matter.',
      ] },
      { id: 'rechte', title: '13. Your privacy rights', paragraphs: [
        'Subject to statutory conditions, you have rights of access (Article 15 GDPR), correction (Article 16), deletion (Article 17), restriction (Article 18) and portability (Article 20). Contact us to exercise them. We may request appropriate information to identify the records and verify your identity.',
        'You can withdraw consent at any time for the future. Withdrawal does not affect the lawfulness of processing based on consent before withdrawal.',
        'For processing under Article 6(1)(f) GDPR, Article 21 GDPR lets you object on grounds relating to your particular situation. We will stop the relevant processing unless compelling legitimate grounds or grounds for legal claims apply. You may object to direct marketing at any time without giving a reason.',
        'Article 77 GDPR lets you complain to a supervisory authority, particularly where you live, work or suspect an infringement. The Bavarian State Office for Data Protection Supervision (BayLDA) is responsible for private companies in Bavaria.',
      ], links: [{ label: 'Submit a complaint to BayLDA', href: 'https://www.lda.bayern.de/de/beschwerde.html' }] },
    ],
  },
};
